---
heat_template_version: 2015-04-30

resources:
  my_network:
    type: OS::Neutron::Net
    properties:
      name: my_network
  
  my_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: my_subnet
      network_id: { get_resource: my_network }
      cidr: 10.0.0.0/24

  my_router:
    type: OS::Neutron::Router
    properties:
      name: my_router

  my_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: my_router }
      subnet_id: { get_resource: my_subnet }
...
