apiVersion: v1
data:
  AdminPassword: UGFzc3cwcmQ=
  CeilometerPassword: UGFzc3cwcmQ=
  CinderDatabasePassword: UGFzc3cwcmQ=
  CinderPassword: UGFzc3cwcmQ=
  DatabasePassword: UGFzc3cwcmQ=
  DbRootPassword: UGFzc3cwcmQ=
  DesignateDatabasePassword: UGFzc3cwcmQ=
  DesignatePassword: UGFzc3cwcmQ=
  GlanceDatabasePassword: UGFzc3cwcmQ=
  GlancePassword: UGFzc3cwcmQ=
  HeatAuthEncryptionKey: UGFzc3cwcmQ=
  HeatDatabasePassword: UGFzc3cwcmQ=
  HeatPassword: UGFzc3cwcmQ=
  IronicDatabasePassword: UGFzc3cwcmQ=
  IronicInspectorDatabasePassword: UGFzc3cwcmQ=
  IronicInspectorPassword: UGFzc3cwcmQ=
  IronicPassword: UGFzc3cwcmQ=
  KeystoneDatabasePassword: UGFzc3cwcmQ=
  ManilaDatabasePassword: UGFzc3cwcmQ=
  ManilaPassword: UGFzc3cwcmQ=
  MetadataSecret: UGFzc3cwcmQ=
  NeutronDatabasePassword: UGFzc3cwcmQ=
  NeutronPassword: UGFzc3cwcmQ=
  NovaAPIDatabasePassword: UGFzc3cwcmQ=
  NovaAPIMessageBusPassword: UGFzc3cwcmQ=
  NovaCell0DatabasePassword: UGFzc3cwcmQ=
  NovaCell0MessageBusPassword: UGFzc3cwcmQ=
  NovaCell1DatabasePassword: UGFzc3cwcmQ=
  NovaCell1MessageBusPassword: UGFzc3cwcmQ=
  NovaPassword: UGFzc3cwcmQ=
  OctaviaDatabasePassword: UGFzc3cwcmQ=
  OctaviaPassword: UGFzc3cwcmQ=
  PlacementDatabasePassword: UGFzc3cwcmQ=
  PlacementPassword: UGFzc3cwcmQ=
  SwiftPassword: UGFzc3cwcmQ=
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
